import { Inter } from "next/font/google";
// import "./globals.css";
import "../globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Deporte local",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <header className="flex items-center justify-center">
                <Navbar/>
      </header>

      {children}

        </body>
    </html>
  );
}
